mysql_config: |
  server_id = 1
  sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DATE,NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION"
  innodb_rollback_on_timeout=1
  innodb_lock_wait_timeout=600
  max_connections=1000
  log-bin=mysql-bin
  binlog-format = 'ROW'
