- block:

  - name: Configure iptables
    iptables:
      chain: INPUT
      source: 192.168.1.254
      protocol: "{{ item.protocol }}"
      match: state
      destination_port: "{{ item.port }}"
      ctstate: NEW
      jump: ACCEPT
      state: present
    with_items: "{{ iptables_config }}"
    register: iptables_check

  - name: Save iptables rules
    shell: netfilter-persistent save
    when: iptables_check.changed

  become: true
