- name: Ajout du repos Cloudstack
  hosts: all
  remote_user: exploit
  roles:
    - role: cs_configure_repo
      tags:
        - cs_configure_repo

- name: Installation de Cloudstack Server
  hosts: server
  remote_user: exploit
  vars:
    packages:
      - bridge-utils
      - cloudstack-management
      - cloudstack-usage
      - mysql-server
      - nfs-kernel-server
  roles:
    - role: install_packages
      tags:
        - install_packages
        - server
    - role: cs_configure_mysql
      tags:
        - cs_configure_mysql
        - server
    - role: cs_configure_nfs
      tags:
        - cs_configure_nfs
        - server
    - role: cs_configure_cloudstack
      tags:
        - cs_configure_cloudstack
        - server

- name: Installation de Cloudstack Client
  hosts: client
  remote_user: exploit
  vars:
    packages:
      - qemu-kvm
      - cloudstack-agent
  roles:
    - role: install_packages
      tags:
        - install_packages
        - client
